/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResultRouteImport } from './routes/result'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewQuizRouteImport } from './routes/review.quiz'
import { Route as ReviewDoneRouteImport } from './routes/review.done'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewQuizRoute = ReviewQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewDoneRoute = ReviewDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => ReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/review': typeof ReviewRouteWithChildren
  '/review/done': typeof ReviewDoneRoute
  '/review/quiz': typeof ReviewQuizRoute
  '/review/': typeof ReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/review/done': typeof ReviewDoneRoute
  '/review/quiz': typeof ReviewQuizRoute
  '/review': typeof ReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/quiz': typeof QuizRoute
  '/result': typeof ResultRoute
  '/review': typeof ReviewRouteWithChildren
  '/review/done': typeof ReviewDoneRoute
  '/review/quiz': typeof ReviewQuizRoute
  '/review/': typeof ReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/quiz'
    | '/result'
    | '/review'
    | '/review/done'
    | '/review/quiz'
    | '/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/quiz'
    | '/result'
    | '/review/done'
    | '/review/quiz'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/quiz'
    | '/result'
    | '/review'
    | '/review/done'
    | '/review/quiz'
    | '/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  QuizRoute: typeof QuizRoute
  ResultRoute: typeof ResultRoute
  ReviewRoute: typeof ReviewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/quiz': {
      id: '/review/quiz'
      path: '/quiz'
      fullPath: '/review/quiz'
      preLoaderRoute: typeof ReviewQuizRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/done': {
      id: '/review/done'
      path: '/done'
      fullPath: '/review/done'
      preLoaderRoute: typeof ReviewDoneRouteImport
      parentRoute: typeof ReviewRoute
    }
  }
}

interface ReviewRouteChildren {
  ReviewDoneRoute: typeof ReviewDoneRoute
  ReviewQuizRoute: typeof ReviewQuizRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewDoneRoute: ReviewDoneRoute,
  ReviewQuizRoute: ReviewQuizRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  QuizRoute: QuizRoute,
  ResultRoute: ResultRoute,
  ReviewRoute: ReviewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
